module.exports =[
  {
    id: 1,
    comment: 'Emma had a great day today. She was very happy and energetic. She was able to complete all her tasks and activities. She was able to eat all her meals and snacks. She was able to sleep for 1 hour.',
    time: '10:00',
    student_id: 1,
    teacher_id: 2,
    log_id: 1,
  },
  {
    id: 2,
    comment: 'Ann had a great day today. She was very happy and energetic. She was able to complete all her tasks and activities. She was able to eat all her meals and snacks.',
    time: '10:00',
    student_id: 2,
    teacher_id: 2,
    log_id: 2,
  },
  {
    id: 3,
    comment: 'Owen had a great day today. He was very happy and energetic. He was able to complete all his tasks and activities. He was able to eat all his meals and snacks. He was able to sleep for 1 hour.',
    time: '10:00',
    student_id: 3,
    teacher_id: 2,
    log_id: 3,
  },
  {
    id: 4,
    comment: 'Athena had a great day today. She was very happy and energetic. She was able to complete all her tasks and activities. She was able to eat all her meals and snacks. She was able to sleep for 1 hour.',
    time: '10:00',
    student_id: 4,
    teacher_id: 1,
    log_id: 4,
  },
  {
    id: 5,
    comment: 'Charleigh had a great day today. She was very happy and energetic. She was able to complete all her tasks and activities. She was able to eat all her meals and snacks.',
    time: '10:00',
    student_id: 5,
    teacher_id: 1,
    log_id: 5,
  },
  {
    id: 6,
    comment: 'Jasper had a great day today. He was very happy and energetic. He was able to complete all his tasks and activities. He was able to eat all his meals and snacks. He was able to sleep for 1 hour.',
    time: '10:00',
    student_id: 6,
    teacher_id: 1,
    log_id: 6,
  },
  {
    id: 7,
    comment: 'Ezra had a great day today. He was very happy and energetic. He was able to complete all his tasks and activities. He was able to eat all his meals and snacks. He was able to sleep for 1 hour.',
    time: '10:00',
    student_id: 7,
    teacher_id: 3,
    log_id: 7,
  },
  {
    id: 8,
    comment: 'Eliana had a great day today. She was very happy and energetic. She was able to complete all her tasks and activities. She was able to eat all her meals and snacks.',
    time: '10:00',
    student_id: 8,
    teacher_id: 3,
    log_id: 8,
  },
  {
    id: 9,
    comment: 'Hannah had a great day today. She was very happy and energetic. She was able to complete all her tasks and activities. She was able to eat all her meals and snacks. She was able to sleep for 1 hour.',
    time: '10:00',
    student_id: 9,
    teacher_id: 3,
    log_id: 9,
  },
]